defaults:
  - scope:
      path: "Markdown"
    values:
      is_markdown: true
      layout: page
exclude:
  - Codes/
  - Html/
  - Json/
lang: ja
markdown: GFM
plugins:
  - jekyll-sitemap
  - jekyll-titles-from-headings