name: Publish

on:
  schedule:
    - cron:  '0 12 * * 4,5'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download and Parse
      run: |
        python Codes/download.py
    - name: Save results
      run: |
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "From GitHub Actions build ${GITHUB_RUN_NUMBER}"
        git push
  archive:
    runs-on: ubuntu-latest
    steps:
    - name: Archive pages
      run: |
        wget "https://web.archive.org/save/https://www.famitsu.com/ranking/game-sales/"
        wget "https://web.archive.org/save/https://www.famitsu.com/ranking/game-sales/last_week/"
        wget "https://web.archive.org/save/https://web.archive.org/save/"