name: Publish

on:
  schedule:
    - cron: '45 14 * * 4,5'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download and Parse
      run: |
        python Codes/download.py
      continue-on-error: true
    - name: Save results
      run: |
        TODAY=$(date +"%FT%H:%M:%S%z")
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "Update: ${TODAY}"
        git push
      continue-on-error: true
